### ISSUE TITLE
can't get pianobar to work with proxy

### ISSUE THREAD

**Issue by oogiedoogie** [thedmd/pianobar-windows-binaries#13]
I cannot get pianobar to work with the proxy. I've used the suggested configuration file, but pianobar just closes as soon as I run it. Any suggestions? My configuration file is plain text. Thanks!

P.S. If you have been able to use pianobar with proxy, could you send me your config file?

**Comment by thedmd** [comment]
Are you using proxy for proxy or control_proxy?

**Comment by oogiedoogie** [comment]
I tried both.... no luck with either. Also, my config file is very 
temperamental - spaces and carriage returns sometimes must be eliminated 
or else pianobar crashes. I assume that the config file should just be 
plain text, right?  I've attached my current config file to this 
message, with * in places of my personal information.

Thanks for your help!
Douglas



On 9/8/2015 11:29 AM, Michał Cichoń wrote:
>
> Are you using proxy for proxy or control_proxy?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thedmd/pianobar-windows-binaries/issues/13#issuecomment-138460672>.
>


control_proxy = http://*****:*********@proxy**.com:8000

user = *****@hotmail.com
password = ******

**Comment by thedmd** [comment]
OK. So control_proxy then. I will check out that.

**Comment by rgobo** [comment]
Any updates or workarounds? I'm still unable to run the latest version using control_proxy.

**Comment by wokawoka** [comment]
I'm experiencing the same problem. The program crashes some seconds after trying to login. 
I'm outside the US and I need to set the proxy, but the program crashes when I try to login after having launched pianobar both with the proper config file and without it (by doing the login directly from the command line).

Is the pianobar on windows abandoned?
Thank you very much!

**Comment by thedmd** [comment]
I thought issue was solved by #16.
@wokawoka Right now I have trouble supporting Windows port since I also do not live in US and I no longer have access to VPN services. Today I have trouble justifying paying for Pandora + VPN. I can look for an solution I you are willing to borrow me an VPN access just for that.
As an alternative I can try to patch pianobar to produce verbose logs (excluding sensitive information).
As a second thought I think a solution which produce mini dump file will be more helpful, this way I should be able to examine state of program when it crashed. I think I will work towards this option. This will take more time but should provide a mechanism to resolve more issues in the future. Please stand by, I should have proper test version of pianobar in a few days.

**Comment by wokawoka** [comment]
Thank you very much for your reply thedmd!
All your ideas sounds very promising.
I'm just using a free Pandora account tough (not Pandora one), and nowadays proxies are quite cheap.
If there was a way to send private messages on github I would send you the credentials for a US proxy in order to let you test the problems.
If you provide me an email address or a way to reach you directly I can send you the details.
Thank you very much again!
W.

**Comment by thedmd** [comment]
Please use email I use with commits on GitHub.
I did some maintenance work and I'm now able to debug the issue.

**Comment by thedmd** [comment]
@wokawoka I found TunnelBear VPN, it has some free quota and I'm able to do tests.
Please try [https://ci.appveyor.com/project/thedmd/pianobar-windows/build/develop-26] build.
I made some fixes, so at least error should be visible now.

**Comment by wokawoka** [comment]
Thank you for your answer.

I did try your new build, I'm no more experiencing the crash, but I'm always receiving the following error:
"Error: Pandora is not available in your country. Set up a control proxy (see manpage)." despite having correctly set up the "control_proxy =" line in the pianobar.cfg file.
It feels like that the "control_proxy =" line is not taken in consideration by the program.

Since I imagine that you are using TunnelBear VPN systemwide and you are not using a proxy like I am (that for example is working perfectly in this right moment with elpis, another pandora client for windows) it would be interesting if you could try using the proxy I'm using, the problem is that I can't find any e-mail address linked with your commits here on Github, and there is no private messaging system here on github.

I would be glad to send you the credentials for a US proxy test account so that you may be able to debug the issue, just let me know how I can reach you directly.

Thank you very much again,
W

**Comment by thedmd** [comment]
@wokawoka Sorry for an edit! I used my phone I accidentally edited your post instead of replying! /o\

From the top of my head, try to remove spaces between. Use `control_proxy=xxx` instead of `control_proxy = xxx`.

If that does not do a trick, my email is michcic, cutesy of Gmail.

**Comment by wokawoka** [comment]
Alright, no problem.
I've tried changing the  control_proxy= string but it didn't work.
I've just send you by email the credentials of a test account for a proxy based in the US.

Thank you again!

**Comment by thedmd** [comment]
@wokawoka I didn't get your mail. Checked spam folder also and it simply isn't there. Did you send it to gmail.com?

**Comment by wokawoka** [comment]
Sorry to hear that, I did send it to the correct address, I believe, but anyway I just sent it again and you should have receiveded already.

**Comment by thedmd** [comment]
I think this should be fixed now. Please check [new release 2017.05.18](https://github.com/thedmd/pianobar-windows/releases/tag/2017.05.18).

If your proxy credentials have special characters you will need to excape them.
Let's assume user is `john.doe@hotmail.com`, and password `Pas$word!'.
To encode them you can use (www.url-encode-decode.com)[http://www.url-encode-decode.com/].
Result will look like this:

`control_proxy = http://john.doe%40hotmail.com:Pas%24word%21@my-vpn.host.com:8080`

Please let me know if this works for you.

**Comment by wokawoka** [comment]
Alright, I've just tried following your instructions but I'm still getting the same error: "Error: Pandora is not available in your country. Set up a control proxy (see manpage)."
My proxy credentials doesn't contain any special character except the @ on the username (that I replaced with %40) but still I can't connect. 
Any suggestion?
Thanks!

**Comment by thedmd** [comment]
I will add some more diagnostic to proxy setup and will let you know.

**Comment by wokawoka** [comment]
Alright, thanks!

**Comment by thedmd** [comment]
Can you try this (https://ci.appveyor.com/api/buildjobs/rjagywahyptm7rq7/artifacts/build%2Fpianobar-feature-control-proxy-32-x64.zip).
There should be more diagnostics around setting control proxy.

**Comment by thedmd** [comment]
Let's summarize:
`control_proxy = <protocol>[<username_url_escaped>:<password_url_escaped>@]<host>[:<port>]`
Where:
`<protocol> = http:// or https://`
`<username_url_escaped> = username encoded by url escape rules`
`<password_url_escaped> = password encoded by url escape rules`
`<host> = host name only like google.com, yahoo.com or IP`
`<port> = optional port number, default port number is determined by protocol`

When you stick to thee rules control proxy setup will work.
